-- ============================================================
-- 炸金花联机版 · Supabase 建表脚本
-- 在 Supabase 控制台 → SQL Editor 里整段运行；新库初始化和旧库升级均可重复执行
-- ============================================================

-- ---------- 房间表 ----------
create table if not exists public.rooms (
  id          uuid primary key default gen_random_uuid(),
  code        text unique not null,          -- 6位房号
  status      text not null default 'waiting', -- waiting / playing / finished
  host_seat   int  not null default 0,       -- 房主座位号
  current_turn int not null default -1,      -- 当前行动玩家座位（-1=无）
  level       int  not null default 0,       -- 当前注额（暗注单位）
  pot         int  not null default 0,       -- 底池
  round       int  not null default 0,       -- 局数（用于触发新一局）
  message     text not null default '',      -- 最近一条操作播报
  msg_seq     int  not null default 0,       -- 播报序号（递增触发实时更新）
  is_public   boolean not null default true, -- 是否出现在公开房间列表
  created_at  timestamptz not null default now()
);
-- 兼容已经运行过旧版脚本的数据库。
alter table public.rooms add column if not exists is_public boolean not null default true;
create index if not exists idx_rooms_public_status
  on public.rooms(is_public, status, created_at desc);

-- ---------- 玩家表（公共状态） ----------
create table if not exists public.players (
  id       uuid primary key default gen_random_uuid(),
  room_id  uuid not null references public.rooms(id) on delete cascade,
  user_id  uuid not null,                    -- 关联匿名登录 uid
  seat     int  not null,
  name     text not null,
  chips    int  not null default 1000,
  seen     boolean not null default false,   -- 是否看牌
  folded   boolean not null default false,   -- 是否弃牌
  bet      int  not null default 0,          -- 本轮注额（不含底注）
  total    int  not null default 0,          -- 本局总投入（含底注，用于边池）
  compare_with int not null default -1,      -- 比牌目标座位（-1=无）
  in_round boolean not null default false,   -- 是否参与当前正在进行的牌局
  is_host  boolean not null default false,
  unique(room_id, seat)
);
-- 兼容已经运行过旧版脚本的数据库。
alter table public.players add column if not exists compare_with int not null default -1;
alter table public.players add column if not exists in_round boolean not null default false;
create index if not exists idx_players_room on public.players(room_id);
create index if not exists idx_players_user on public.players(user_id);

-- ---------- 手牌表（RLS 保护隐私） ----------
create table if not exists public.hands (
  player_id uuid primary key references public.players(id) on delete cascade,
  user_id   uuid not null,
  room_id   uuid not null,
  hand      jsonb                          -- [{rank,suit},...] 或 null
);
create index if not exists idx_hands_room on public.hands(room_id);

-- ---------- 聊天消息表 ----------
create table if not exists public.messages (
  id         bigint generated by default as identity primary key,
  room_id    uuid not null references public.rooms(id) on delete cascade,
  name       text not null,
  text       text not null,
  created_at timestamptz not null default now()
);
create index if not exists idx_messages_room_created
  on public.messages(room_id, created_at);

-- ============================================================
-- 行级安全 RLS
-- ============================================================
alter table public.rooms   enable row level security;
alter table public.players enable row level security;
alter table public.hands   enable row level security;
alter table public.messages enable row level security;

-- rooms / players：好友房信任模型，匿名可读写（简化，便于快速上线）
drop policy if exists "rooms_all" on public.rooms;
create policy "rooms_all"   on public.rooms   for all using (true) with check (true);
drop policy if exists "players_all" on public.players;
create policy "players_all" on public.players for all using (true) with check (true);
drop policy if exists "messages_all" on public.messages;
create policy "messages_all" on public.messages for all using (true) with check (true);

-- hands：普通玩家只能读自己的手牌；房主可读全桌手牌
drop policy if exists "hands_read_own" on public.hands;
create policy "hands_read_own" on public.hands for select
  using (auth.uid() = user_id);

drop policy if exists "hands_read_host" on public.hands;
create policy "hands_read_host" on public.hands for select
  using (
    exists (
      select 1 from public.players p
      where p.room_id = hands.room_id
        and p.user_id = auth.uid()
        and p.is_host
    )
  );

-- hands：写权限（房主洗牌发牌时写入所有人的手牌）
drop policy if exists "hands_insert_host" on public.hands;
create policy "hands_insert_host" on public.hands for insert
  with check (
    exists (
      select 1 from public.players p
      where p.room_id = hands.room_id
        and p.user_id = auth.uid()
        and p.is_host
    )
  );

-- hands：更新（房主结算后清空手牌）
drop policy if exists "hands_update_host" on public.hands;
create policy "hands_update_host" on public.hands for update
  using (
    exists (
      select 1 from public.players p
      where p.room_id = hands.room_id
        and p.user_id = auth.uid()
        and p.is_host
    )
  );

-- ============================================================
-- 实时订阅（Realtime）
-- 建表后需要把这几个表加入 publication 才能收到 postgres_changes
-- ============================================================
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='rooms'
  ) then
    alter publication supabase_realtime add table public.rooms;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='players'
  ) then
    alter publication supabase_realtime add table public.players;
  end if;
  if not exists (
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='hands'
  ) then
    alter publication supabase_realtime add table public.hands;
  end if;
end;
$$;

-- ============================================================
-- 辅助函数：生成 6 位房号（避免冲突）
-- ============================================================
create or replace function public.gen_room_code()
returns text language plpgsql as $$
declare
  code text;
begin
  loop
    code := upper(substr(md5(random()::text), 1, 6));
    exit when not exists (select 1 from public.rooms r where r.code = code);
  end loop;
  return code;
end;
$$;
