-- Zhajinhua server schema. Run this migration before 002_indexes.sql.
-- PostgreSQL 16+, with UUIDs generated by pgcrypto.
CREATE EXTENSION IF NOT EXISTS pgcrypto;

create table if not exists users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT,
  password_hash TEXT,
  nickname TEXT NOT NULL,
  beans BIGINT NOT NULL DEFAULT 100000 CHECK (beans >= 0),
  wins BIGINT NOT NULL DEFAULT 0 CHECK (wins >= 0),
  losses BIGINT NOT NULL DEFAULT 0 CHECK (losses >= 0),
  music_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  effects_enabled BOOLEAN NOT NULL DEFAULT TRUE,
  animation_mode TEXT NOT NULL DEFAULT 'light'
    CHECK (animation_mode IN ('light', 'cinematic', 'disabled')),
  refill_generation BIGINT NOT NULL DEFAULT 0 CHECK (refill_generation >= 0),
  last_zero_generation BIGINT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT users_password_or_legacy CHECK (password_hash IS NOT NULL OR email IS NULL)
);

-- Email is nullable for an imported anonymous account until it is claimed.
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_unique
  ON users (lower(email)) WHERE email IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS users_nickname_lower_unique
  ON users (lower(nickname));

create table if not exists sessions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  token_hash BYTEA NOT NULL UNIQUE,
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  revoked_at TIMESTAMPTZ
);

create table if not exists rooms (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  code TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'waiting'
    CHECK (status IN ('waiting', 'dealing', 'betting', 'comparing', 'settled', 'finished')),
  host_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  dealer_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  dealer_seat INTEGER CHECK (dealer_seat BETWEEN 0 AND 7),
  current_turn INTEGER NOT NULL DEFAULT -1 CHECK (current_turn BETWEEN -1 AND 7),
  ante BIGINT NOT NULL DEFAULT 10 CHECK (ante >= 0),
  level BIGINT NOT NULL DEFAULT 0 CHECK (level >= 0),
  pot BIGINT NOT NULL DEFAULT 0 CHECK (pot >= 0),
  round_number INTEGER NOT NULL DEFAULT 0 CHECK (round_number >= 0),
  is_public BOOLEAN NOT NULL DEFAULT TRUE,
  allow_spectators BOOLEAN NOT NULL DEFAULT FALSE,
  version BIGINT NOT NULL DEFAULT 0 CHECK (version >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

create table if not exists room_players (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id UUID NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  seat INTEGER NOT NULL CHECK (seat BETWEEN 0 AND 7),
  nickname TEXT NOT NULL,
  in_round BOOLEAN NOT NULL DEFAULT FALSE,
  folded BOOLEAN NOT NULL DEFAULT FALSE,
  all_in BOOLEAN NOT NULL DEFAULT FALSE,
  seen BOOLEAN NOT NULL DEFAULT FALSE,
  current_bet BIGINT NOT NULL DEFAULT 0 CHECK (current_bet >= 0),
  total_contribution BIGINT NOT NULL DEFAULT 0 CHECK (total_contribution >= 0),
  action_seq BIGINT NOT NULL DEFAULT 0 CHECK (action_seq >= 0),
  last_action TEXT,
  compare_with UUID REFERENCES room_players(id) ON DELETE SET NULL,
  left_room BOOLEAN NOT NULL DEFAULT FALSE,
  is_host BOOLEAN NOT NULL DEFAULT FALSE,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (room_id, seat)
);

-- An account cannot occupy two active seats, even in different rooms.
CREATE UNIQUE INDEX IF NOT EXISTS active_room_players_user_unique
  ON room_players (user_id) WHERE left_room = FALSE;

create table if not exists room_spectators (
  room_id UUID NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  joined_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (room_id, user_id)
);

create table if not exists rounds (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  room_id UUID NOT NULL REFERENCES rooms(id) ON DELETE CASCADE,
  round_number INTEGER NOT NULL CHECK (round_number > 0),
  status TEXT NOT NULL DEFAULT 'dealing'
    CHECK (status IN ('dealing', 'betting', 'comparing', 'settled')),
  dealer_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  dealer_seat INTEGER CHECK (dealer_seat BETWEEN 0 AND 7),
  current_turn INTEGER NOT NULL DEFAULT -1 CHECK (current_turn BETWEEN -1 AND 7),
  ante BIGINT NOT NULL DEFAULT 0 CHECK (ante >= 0),
  pot BIGINT NOT NULL DEFAULT 0 CHECK (pot >= 0),
  state JSONB NOT NULL DEFAULT '{}'::jsonb,
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  settled_at TIMESTAMPTZ,
  UNIQUE (room_id, round_number)
);

create table if not exists round_players (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  round_id UUID NOT NULL REFERENCES rounds(id) ON DELETE CASCADE,
  room_player_id UUID REFERENCES room_players(id) ON DELETE SET NULL,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  seat INTEGER NOT NULL CHECK (seat BETWEEN 0 AND 7),
  hand JSONB,
  hand_type TEXT,
  hand_visible BOOLEAN NOT NULL DEFAULT FALSE,
  folded BOOLEAN NOT NULL DEFAULT FALSE,
  all_in BOOLEAN NOT NULL DEFAULT FALSE,
  total_contribution BIGINT NOT NULL DEFAULT 0 CHECK (total_contribution >= 0),
  payout BIGINT NOT NULL DEFAULT 0 CHECK (payout >= 0),
  net_change BIGINT NOT NULL DEFAULT 0,
  result TEXT CHECK (result IN ('win', 'loss', 'tie')),
  action_count INTEGER NOT NULL DEFAULT 0 CHECK (action_count >= 0),
  UNIQUE (round_id, user_id),
  UNIQUE (round_id, seat)
);

create table if not exists account_ledger (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE RESTRICT,
  round_id UUID REFERENCES rounds(id) ON DELETE SET NULL,
  entry_type TEXT NOT NULL
    CHECK (entry_type IN ('ante', 'bet', 'compare_fee', 'payout', 'refill', 'adjustment', 'refund')),
  amount BIGINT NOT NULL CHECK (amount <> 0),
  idempotency_key TEXT NOT NULL,
  balance_after BIGINT CHECK (balance_after >= 0),
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (idempotency_key)
);

create table if not exists game_events (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  room_id UUID REFERENCES rooms(id) ON DELETE CASCADE,
  round_id UUID REFERENCES rounds(id) ON DELETE CASCADE,
  event_type TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  audience TEXT NOT NULL DEFAULT 'room'
    CHECK (audience IN ('room', 'global', 'both')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

create table if not exists global_banners (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  queue_name TEXT NOT NULL CHECK (queue_name IN ('economy', 'leaderboard')),
  banner_type TEXT NOT NULL,
  message TEXT NOT NULL,
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

create table if not exists legacy_migrations (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  provider TEXT NOT NULL DEFAULT 'supabase',
  legacy_user_id TEXT NOT NULL,
  target_user_id UUID REFERENCES users(id) ON DELETE SET NULL,
  source_balance BIGINT NOT NULL DEFAULT 0 CHECK (source_balance >= 0),
  source_wins BIGINT NOT NULL DEFAULT 0 CHECK (source_wins >= 0),
  source_losses BIGINT NOT NULL DEFAULT 0 CHECK (source_losses >= 0),
  status TEXT NOT NULL DEFAULT 'pending'
    CHECK (status IN ('pending', 'claimed', 'merged', 'failed')),
  claim_token_hash BYTEA,
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  migrated_at TIMESTAMPTZ,
  UNIQUE (provider, legacy_user_id)
);

CREATE OR REPLACE FUNCTION set_zhajinhua_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_users_updated_at ON users;
CREATE TRIGGER trg_users_updated_at BEFORE UPDATE ON users
FOR EACH ROW EXECUTE FUNCTION set_zhajinhua_updated_at();
DROP TRIGGER IF EXISTS trg_rooms_updated_at ON rooms;
CREATE TRIGGER trg_rooms_updated_at BEFORE UPDATE ON rooms
FOR EACH ROW EXECUTE FUNCTION set_zhajinhua_updated_at();
DROP TRIGGER IF EXISTS trg_room_players_updated_at ON room_players;
CREATE TRIGGER trg_room_players_updated_at BEFORE UPDATE ON room_players
FOR EACH ROW EXECUTE FUNCTION set_zhajinhua_updated_at();

-- Events are inserted in the same transaction as the state change. PostgreSQL
-- delivers NOTIFY payloads only after that transaction commits.
CREATE OR REPLACE FUNCTION notify_game_event()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  PERFORM pg_notify('zhajinhua_events',
    json_build_object('event_id', NEW.id, 'room_id', NEW.room_id,
                      'event_type', NEW.event_type)::text
  );
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_game_events_notify ON game_events;
CREATE TRIGGER trg_game_events_notify AFTER INSERT ON game_events
FOR EACH ROW EXECUTE FUNCTION notify_game_event();

CREATE OR REPLACE FUNCTION prevent_ledger_mutation()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'ACCOUNT_LEDGER_IMMUTABLE';
END;
$$;

DROP TRIGGER IF EXISTS trg_account_ledger_immutable ON account_ledger;
CREATE TRIGGER trg_account_ledger_immutable
BEFORE UPDATE OR DELETE ON account_ledger
FOR EACH ROW EXECUTE FUNCTION prevent_ledger_mutation();
